<?php
/**
 * Generate email template's footer 
 *
 * @category    Aydus
 * @package     Aydus_Emailheaderfooter
 * @author		Aydus <davidt@aydus.com>
 */
?>
<table cellspacing="0" cellpadding="0" border="0" width="100%">
	<tbody>
		<tr align="center" >
			<td>
			Copyright &copy; <?php echo date("Y")?> <?php echo Mage::getStoreConfig('general/store_information/name'); ?>. All rights reserved.
			</td>
		</tr>
	</tbody>
</table>